import { useEffect, useMemo, useState } from 'react';
import { Check, Copy, ExternalLink, Lock, Plus, Search, Trash2 } from 'lucide-react';

import { AdminPage, DataState, IconAction, SaveBar } from '@components/admin';
import { Button, Card, Input, Switch, Textarea } from '@components/ui';
import { useAuth } from '@context/AuthContext.jsx';
import { useToast } from '@context/ToastContext.jsx';
import { useAsyncData } from '@hooks/useAsyncData.js';
import { canEditSetting, listSettings, updateSetting } from '@services/settingsService.js';
import { updateOwnName } from '@services/usersService.js';
import { SETTINGS_KEYS } from '@utils/constants.js';
import { env } from '@utils/env.js';
import { organizationSchema } from '@utils/schema.js';

/* ================================================================
   SEO SETTINGS (Dashboard spec §6, §12 — client notes ٦, ٧, ٨)

   RENAMED FROM "الإعدادات" (note ٦)
   ----------------------------------------------------------------
   "إعادة تسمية زر «إعدادات» … إلى: إعدادات SEO، بحيث يضم هذا القسم
    إعدادات السيو العامة للموقع."

   The route is unchanged (/admin/settings) so existing bookmarks and
   the version history's links still resolve; only the label and the
   framing moved. What the screen now holds, in order: the schema, the
   accounts that feed its `sameAs`, robots.txt, the sitemap, then the
   two things that were already here and have nowhere better to live
   (the consent banner, and your own display name).

   THE SCHEMA IS EDITABLE, AND IT IS NOW ACTUALLY EMITTED (note ٦)
   ----------------------------------------------------------------
   "جعل جميع إعدادات وبيانات الـ Schema الموجودة حاليًا قابلة للتعديل
    … التأكد من أن الـ Schema … يتم توليدها بشكل صحيح وتعمل على مستوى
    الموقع بصيغة Organization Schema."

   Two separate faults behind that sentence, both fixed:

     1. The block had five fields — name, legal name, URL, email,
        logo — and schema.org/Organization wants rather more. The
        missing ones (description, telephone, founding date, a real
        PostalAddress) are now here, all editable, all saved.
     2. NOTHING RENDERED IT. There was no JSON-LD on the site at all,
        so "the schema is not editable" was the visible half of "the
        schema does not exist". `utils/schema.js` builds it from
        these values and `components/layout/SiteHead.jsx` puts it in
        the head of every public page.

   The live preview at the bottom of that card is the receipt: it is
   the exact object that will be published, generated by the same
   function, so a field left blank is visibly absent rather than
   silently defaulted.
   ================================================================ */

const KEYS = [
  SETTINGS_KEYS.ORGANIZATION,
  SETTINGS_KEYS.SOCIAL,
  SETTINGS_KEYS.CONSENT,
  SETTINGS_KEYS.SEO,
];

function readValues(rows) {
  return {
    [SETTINGS_KEYS.ORGANIZATION]: rows.get(SETTINGS_KEYS.ORGANIZATION)?.value ?? {},
    [SETTINGS_KEYS.SOCIAL]: rows.get(SETTINGS_KEYS.SOCIAL)?.value ?? [],
    [SETTINGS_KEYS.CONSENT]: rows.get(SETTINGS_KEYS.CONSENT)?.value ?? {},
    [SETTINGS_KEYS.SEO]: rows.get(SETTINGS_KEYS.SEO)?.value ?? {},
  };
}

/** Every Organization field, in the order they are entered. */
const ORGANIZATION_FIELDS = [
  ['name', 'الاسم المختصر', 'rtl', 'الاسم كما يظهر في نتائج البحث.'],
  ['legalName', 'الاسم الرسمي', 'rtl', 'الاسم المسجَّل رسمياً للمؤسسة.'],
  ['alternateName', 'اسم بديل', 'rtl', 'اسم آخر تُعرف به المنصة، إن وُجد.'],
  ['url', 'العنوان الإلكتروني للموقع', 'ltr', 'العنوان الكامل مع https.'],
  ['logo', 'رابط الشعار', 'ltr', 'رابط كامل أو مسار يبدأ بـ / — يُحوَّل إلى رابط كامل تلقائياً.'],
  ['email', 'البريد الإلكتروني', 'ltr', ''],
  ['telephone', 'رقم الهاتف', 'ltr', 'بصيغة دولية، مثل ‎+31201234567.'],
  ['foundingDate', 'تاريخ التأسيس', 'ltr', 'بصيغة YYYY-MM-DD أو YYYY.'],
];

const ADDRESS_FIELDS = [
  ['streetAddress', 'الشارع'],
  ['addressLocality', 'المدينة'],
  ['addressRegion', 'المنطقة / المحافظة'],
  ['postalCode', 'الرمز البريدي'],
  ['addressCountry', 'الدولة (رمز من حرفين مثل NL)'],
];

export default function Settings() {
  const toast = useToast();
  const { role, profile } = useAuth();
  const [saving, setSaving] = useState(false);

  const { data, loading, error, reload } = useAsyncData(() => listSettings(KEYS), 'settings');

  const [loaded, setLoaded] = useState(null);
  const [form, setForm] = useState(null);
  if (data && data !== loaded) {
    setLoaded(data);
    setForm(readValues(data));
  }

  const baseline = useMemo(() => (loaded ? readValues(loaded) : null), [loaded]);
  const dirty = Boolean(form && baseline) && JSON.stringify(form) !== JSON.stringify(baseline);
  const editable = Boolean(loaded && canEditSetting(loaded.get(SETTINGS_KEYS.ORGANIZATION), role));

  useEffect(() => {
    document.title = 'إعدادات SEO | لوحة تحكم بدار';
  }, []);

  const setOrganization = (patch) =>
    setForm((current) => ({
      ...current,
      organization: { ...current.organization, ...patch },
    }));

  const setConsent = (patch) =>
    setForm((current) => ({ ...current, consent: { ...current.consent, ...patch } }));

  const setSeo = (patch) =>
    setForm((current) => ({ ...current, seo: { ...current.seo, ...patch } }));

  const save = async () => {
    setSaving(true);
    try {
      for (const key of KEYS) {
        if (JSON.stringify(form[key]) !== JSON.stringify(baseline[key])) {
          await updateSetting(key, form[key]);
        }
      }
      reload();
      toast.success('تم حفظ الإعدادات.');
    } catch (caught) {
      toast.failure(caught);
    } finally {
      setSaving(false);
    }
  };

  /* Exactly what the site will publish — same function, same input.
     A preview built any other way is a second implementation that
     drifts from the one that ships. */
  const schemaPreview = useMemo(() => {
    if (!form) return null;
    return organizationSchema({ ...form.organization, social: form.social });
  }, [form]);

  const siteUrl = (form?.organization?.url || env.siteUrl || '').replace(/\/+$/, '');

  return (
    <AdminPage
      eyebrow="الإدارة"
      icon={Search}
      title="إعدادات SEO"
      description="البيانات المنظّمة وملف robots.txt وخريطة الموقع — تُدخل مرة واحدة وتُطبَّق على الموقع كاملاً."
    >
      {!editable ? (
        <p className="flex items-start gap-2 rounded-md bg-sunken px-4 py-3 text-xs leading-relaxed text-ink-secondary">
          <Lock className="mt-0.5 size-4 shrink-0 text-ink-muted" aria-hidden="true" />
          إعدادات السيو وبيانات المنصة للمديرين فقط. يمكنك تعديل اسمك المعروض من البطاقة في أسفل
          الصفحة.
        </p>
      ) : null}

      <DataState loading={loading} error={error} onRetry={reload} empty={!form}>
        {form ? (
          <div className="flex flex-col gap-5">
            {/* ── Note ٦ ─────────────────────────────────────── */}
            <Card className="gap-5">
              <h2 className="text-base font-bold text-ink">
                بيانات المنظّمة (Organization Schema)
              </h2>
              <p className="-mt-3 text-xs leading-relaxed text-ink-muted">
                تُولَّد منها البيانات المنظّمة التي تقرأها محركات البحث، وتُضاف تلقائياً إلى كل
                صفحات الموقع. الحقول الفارغة تُحذف من البيانات المنشورة ولا تُملأ بقيم افتراضية.
              </p>

              <div className="grid gap-4 sm:grid-cols-2">
                {ORGANIZATION_FIELDS.map(([key, label, dir, hint]) => (
                  <Input
                    key={key}
                    label={label}
                    dir={dir}
                    hint={hint || undefined}
                    disabled={!editable}
                    value={form.organization[key] ?? ''}
                    onChange={(event) =>
                      setOrganization({
                        [key]: dir === 'ltr' ? event.target.value.trim() : event.target.value,
                      })
                    }
                  />
                ))}
              </div>

              <Textarea
                label="وصف المنظّمة"
                rows={3}
                disabled={!editable}
                value={form.organization.description ?? ''}
                onChange={(event) => setOrganization({ description: event.target.value })}
                hint="جملتان تعرّفان بالمنصة. تظهر ضمن البيانات المنظّمة، لا على الصفحة."
              />

              <fieldset className="flex flex-col gap-3 rounded-md border border-subtle p-3">
                <legend className="px-1 text-[13px] font-semibold text-ink">العنوان</legend>
                <p className="text-xs leading-relaxed text-ink-muted">
                  يُنشر كـ PostalAddress. اتركه فارغاً بالكامل إن لم يكن للمؤسسة عنوان معلن — عنوان
                  ناقص يُسجَّل كتحذير في أدوات جوجل.
                </p>
                <div className="grid gap-3 sm:grid-cols-2">
                  {ADDRESS_FIELDS.map(([key, label]) => (
                    <Input
                      key={key}
                      label={label}
                      disabled={!editable}
                      value={form.organization[key] ?? ''}
                      onChange={(event) => setOrganization({ [key]: event.target.value })}
                    />
                  ))}
                </div>
              </fieldset>

              <SchemaPreview schema={schemaPreview} />
            </Card>

            <Card className="gap-5">
              <h2 className="text-base font-bold text-ink">حسابات التواصل الاجتماعي</h2>
              <p className="-mt-3 text-xs leading-relaxed text-ink-muted">
                تظهر في الفوتر، وتُدرج ضمن البيانات المنظّمة في الحقل{' '}
                <span className="ltr-run">sameAs</span> كحسابات رسمية للمنصة.
              </p>

              <ul className="flex flex-col gap-3">
                {(form.social ?? []).map((account, index) => (
                  <li
                    key={account.id ?? index}
                    className="flex flex-col gap-3 rounded-md border border-subtle p-3"
                  >
                    <div className="flex items-center justify-between gap-2">
                      <span className="text-xs font-semibold text-ink-muted">
                        {account.label || `حساب ${index + 1}`}
                      </span>
                      {editable ? (
                        <IconAction
                          label="حذف الحساب"
                          icon={Trash2}
                          danger
                          onClick={() =>
                            setForm({
                              ...form,
                              social: form.social.filter((_, position) => position !== index),
                            })
                          }
                        />
                      ) : null}
                    </div>

                    <div className="grid gap-3 sm:grid-cols-3">
                      {[
                        ['label', 'المنصة', 'rtl'],
                        ['handle', 'المعرّف', 'ltr'],
                        ['href', 'الرابط', 'ltr'],
                      ].map(([key, label, dir]) => (
                        <Input
                          key={key}
                          label={label}
                          dir={dir}
                          disabled={!editable}
                          value={account[key] ?? ''}
                          onChange={(event) =>
                            setForm({
                              ...form,
                              social: form.social.map((item, position) =>
                                position === index ? { ...item, [key]: event.target.value } : item,
                              ),
                            })
                          }
                        />
                      ))}
                    </div>
                  </li>
                ))}
              </ul>

              {editable ? (
                <div>
                  <Button
                    variant="secondary"
                    size="sm"
                    onClick={() =>
                      setForm({
                        ...form,
                        social: [
                          ...(form.social ?? []),
                          {
                            id: `account-${(form.social ?? []).length + 1}`,
                            label: '',
                            handle: '',
                            href: '',
                          },
                        ],
                      })
                    }
                  >
                    <Plus className="size-4" aria-hidden="true" />
                    إضافة حساب
                  </Button>
                </div>
              ) : null}
            </Card>

            {/* ── Note ٧ ─────────────────────────────────────── */}
            <Card className="gap-5">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <h2 className="text-base font-bold text-ink">
                  ملف <span className="ltr-run">robots.txt</span>
                </h2>
                <Button
                  variant="ghost"
                  size="sm"
                  href={`${siteUrl}/robots.txt`}
                  target="_blank"
                  rel="noreferrer"
                >
                  <ExternalLink className="size-4" aria-hidden="true" />
                  عرض الملف الحالي
                </Button>
              </div>
              <p className="-mt-3 text-xs leading-relaxed text-ink-muted">
                ما يُحفظ هنا هو محتوى الملف الفعلي المتاح على{' '}
                <span className="ltr-run">/robots.txt</span> — يُطبَّق فور الحفظ دون تعديل برمجي.
              </p>

              <Textarea
                label="تعليمات محركات البحث"
                dir="ltr"
                rows={8}
                disabled={!editable}
                value={form.seo.robotsTxt ?? ''}
                onChange={(event) => setSeo({ robotsTxt: event.target.value })}
                className="font-mono text-xs"
                hint="اتركه فارغاً لاستخدام الإعداد الافتراضي: السماح لكل محركات البحث بفهرسة الموقع."
              />

              <Switch
                label="إضافة سطر Sitemap تلقائياً"
                checked={form.seo.robotsIncludeSitemap !== false}
                disabled={!editable}
                onChange={(event) => setSeo({ robotsIncludeSitemap: event.target.checked })}
              />
              <p className="-mt-3 text-xs leading-relaxed text-ink-muted">
                يُضاف السطر <span className="ltr-run">Sitemap: {siteUrl}/sitemap.xml</span> إلى
                نهاية الملف، ما لم يكن مكتوباً فيه أصلاً.
              </p>
            </Card>

            {/* ── Note ٨ ─────────────────────────────────────── */}
            <Card className="gap-5">
              <h2 className="text-base font-bold text-ink">
                خريطة الموقع <span className="ltr-run">(Sitemap)</span>
              </h2>
              <p className="-mt-3 text-xs leading-relaxed text-ink-muted">
                تُبنى تلقائياً من المحتوى المنشور: كل صفحة أو مقال أو خبر أو برنامج يُنشر يُضاف، وكل
                ما يُحذف أو يُلغى نشره يُزال — دون أي تدخّل. الصفحات التي فُعّل عليها خيار «إخفاء من
                محركات البحث» لا تُدرَج.
              </p>

              <CopyField label="رابط خريطة الموقع" value={`${siteUrl}/sitemap.xml`} />

              <div className="grid gap-4 sm:grid-cols-2">
                <Input
                  label="تكرار التحديث (changefreq)"
                  dir="ltr"
                  disabled={!editable}
                  value={form.seo.sitemapChangefreq ?? 'weekly'}
                  onChange={(event) => setSeo({ sitemapChangefreq: event.target.value.trim() })}
                  hint="daily · weekly · monthly — تلميح إرشادي لمحركات البحث."
                />
                <Input
                  label="الأولوية (priority)"
                  dir="ltr"
                  disabled={!editable}
                  value={form.seo.sitemapPriority ?? '0.7'}
                  onChange={(event) => setSeo({ sitemapPriority: event.target.value.trim() })}
                  hint="قيمة بين 0.0 و 1.0."
                />
              </div>
            </Card>

            <Card className="gap-5">
              <h2 className="text-base font-bold text-ink">الموافقة على ملفات تعريف الارتباط</h2>
              <p className="-mt-3 text-xs leading-relaxed text-ink-muted">
                مؤسسة منار مسجَّلة في هولندا، فتطبَّق اللائحة الأوروبية على الزوّار جميعاً بغضّ
                النظر عن بلدهم.
              </p>

              <Switch
                label="إظهار شريط الموافقة"
                checked={Boolean(form.consent.enabled)}
                disabled={!editable}
                onChange={(event) => setConsent({ enabled: event.target.checked })}
              />

              <div className="grid gap-4 sm:grid-cols-2">
                <Input
                  label="رابط سياسة الخصوصية"
                  dir="ltr"
                  disabled={!editable}
                  value={form.consent.privacyPolicyHref ?? ''}
                  onChange={(event) => setConsent({ privacyPolicyHref: event.target.value.trim() })}
                />
                <Input
                  label="رابط سياسة ملفات تعريف الارتباط"
                  dir="ltr"
                  disabled={!editable}
                  value={form.consent.cookiePolicyHref ?? ''}
                  onChange={(event) => setConsent({ cookiePolicyHref: event.target.value.trim() })}
                />
              </div>
            </Card>

            <AccountCard profile={profile} />

            <SaveBar
              dirty={dirty}
              saving={saving}
              onSave={save}
              onReset={() => setForm(baseline)}
            />
          </div>
        ) : null}
      </DataState>
    </AdminPage>
  );
}

/**
 * The JSON-LD that will be published, live as the fields change.
 *
 * Rendered as text inside a `<pre>` — React escapes it, so this is a
 * display of the object and never a second copy of it running.
 */
function SchemaPreview({ schema }) {
  if (!schema) {
    return (
      <p className="rounded-md bg-warning-100 px-4 py-3 text-xs leading-relaxed text-warning-700">
        لن تُنشر بيانات منظّمة حتى يُملأ اسم المنصة أو عنوان الموقع على الأقل.
      </p>
    );
  }

  return (
    <details className="rounded-md border border-subtle bg-sunken">
      <summary className="cursor-pointer px-4 py-3 text-[13px] font-semibold text-ink">
        معاينة البيانات المنظّمة التي ستُنشر
      </summary>
      <pre
        dir="ltr"
        className="max-h-96 overflow-auto px-4 pb-4 text-start font-mono text-[11px] leading-relaxed text-ink-secondary"
      >
        {JSON.stringify(schema, null, 2)}
      </pre>
    </details>
  );
}

/**
 * A read-only value with a copy button — note ٨ asks for the sitemap
 * URL to be shown "بشكل واضح لتسهيل نسخه واستخدامه لاحقًا في Google
 * Search Console", and selecting an LTR URL out of an RTL layout by
 * hand is exactly the fiddly step that request is about.
 */
function CopyField({ label, value }) {
  const [copied, setCopied] = useState(false);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      /* clipboard blocked — the value is on screen and selectable */
    }
  };

  return (
    <div className="flex flex-wrap items-end gap-2">
      <Input label={label} dir="ltr" value={value} readOnly fieldClassName="min-w-64 flex-1" />
      <Button variant="secondary" size="sm" onClick={copy}>
        {copied ? (
          <Check className="size-4" aria-hidden="true" />
        ) : (
          <Copy className="size-4" aria-hidden="true" />
        )}
        {copied ? 'تم النسخ' : 'نسخ'}
      </Button>
    </div>
  );
}

/**
 * Own display name — the one thing on this screen an editor may
 * always change. It saves on its own rather than through the shared
 * bar, because it writes to `profiles` and not to `site_settings`.
 */
function AccountCard({ profile }) {
  const toast = useToast();
  const [name, setName] = useState(null);
  const [busy, setBusy] = useState(false);

  const [source, setSource] = useState(null);
  if (profile !== source) {
    setSource(profile);
    setName(profile?.full_name ?? '');
  }

  const save = async () => {
    setBusy(true);
    try {
      await updateOwnName(profile.id, name.trim());
      toast.success('تم حفظ الاسم.');
    } catch (caught) {
      toast.failure(caught);
    } finally {
      setBusy(false);
    }
  };

  if (!profile) return null;

  return (
    <Card className="gap-5">
      <h2 className="text-base font-bold text-ink">حسابي</h2>
      <div className="flex flex-wrap items-end gap-3">
        <Input
          label="الاسم المعروض"
          value={name ?? ''}
          onChange={(event) => setName(event.target.value)}
          fieldClassName="min-w-56 max-w-80 flex-1"
          hint={`البريد المرتبط بالحساب: ${profile.email}`}
        />
        <Button
          size="sm"
          onClick={save}
          loading={busy}
          disabled={busy || name === profile.full_name}
        >
          حفظ الاسم
        </Button>
      </div>
    </Card>
  );
}
